# server:
#   port: 8081

eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER

    

spring:
  servlet:
    multipart: 
      max-file-size: 10MB
 
      max-request-size: 10MB
      
outPath: C:\Users\SivakumarK\Documents\FfmpegTrial\video_out
ffmpegCmd: cmd /c ffmpeg -i  
