server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

spring:
  servlet:
    multipart: 
      max-file-size: 10MB
 
      max-request-size: 10MB
      
path: C:\\Users\\SivakumarK\\Documents\\FfmpegTrial\\video_out
