server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: CONVERTER-SERVICE


  servlet:
    multipart: 
      max-file-size: 10MB
 
      max-request-size: 10MB
      

Out:
  Path: C:\\Users\\SivakumarK\\Documents\\FfmpegTrial\\video_out\\
